micronaut:
  application:
    name: demo
  server:
    port: 8086
netty:
  default:
    allocator:
      max-order: 3
endpoints:
  beans:
    enabled: true
    sensitive: true 
  info:
    enabled: true
    sensitive: false